---
application:
  name: "dummy-express-app"
  project: "dummy-express-app"
  organization: "QoveryCommunity"
  port: 3000
routers:
- name: "main-dummy-express-app"
  routes:
  - application_name: "dummy-express-app"
    paths:
    - "/*"
