---
application:
  name: "prod"
  project: "dummy-express-app"
  organization: "My Organization"
  port: 3000
routers:
- name: "main-prod"
  routes:
  - application_name: "prod"
    paths:
    - "/*"
